package com.blog.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;
@Table(name = "blog_user")
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gw_user.u_id
     *
     * @mbggenerated
     */
    @Id
    private String u_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gw_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gw_user.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gw_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gw_user.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gw_user.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gw_user.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gw_user.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gw_user
     *
     * @mbggenerated
     */
    public User(String u_id, String name, String phoneNumber, String email, String className, String department, String introduction, Date date) {
        this.u_id = u_id;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.className = className;
        this.department = department;
        this.introduction = introduction;
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gw_user
     *
     * @mbggenerated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gw_user.u_id
     *
     * @return the value of gw_user.u_id
     *
     * @mbggenerated
     */
    public String getu_id() {
        return u_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gw_user.u_id
     *
     * @param u_id the value for gw_user.u_id
     *
     * @mbggenerated
     */
    public void setu_id(String u_id) {
        this.u_id = u_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gw_user.name
     *
     * @return the value of gw_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gw_user.name
     *
     * @param name the value for gw_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gw_user.phone_number
     *
     * @return the value of gw_user.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gw_user.phone_number
     *
     * @param phoneNumber the value for gw_user.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gw_user.email
     *
     * @return the value of gw_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gw_user.email
     *
     * @param email the value for gw_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gw_user.class_name
     *
     * @return the value of gw_user.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gw_user.class_name
     *
     * @param className the value for gw_user.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gw_user.department
     *
     * @return the value of gw_user.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gw_user.department
     *
     * @param department the value for gw_user.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gw_user.introduction
     *
     * @return the value of gw_user.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gw_user.introduction
     *
     * @param introduction the value for gw_user.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gw_user.date
     *
     * @return the value of gw_user.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gw_user.date
     *
     * @param date the value for gw_user.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    @Override
    public String toString() {
        return "User{" +
                "u_id='" + u_id + '\'' +
                ", name='" + name + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", email='" + email + '\'' +
                ", className='" + className + '\'' +
                ", department='" + department + '\'' +
                ", introduction='" + introduction + '\'' +
                ", date=" + date +
                '}';
    }
}